name: nodejs-github-actions-study
on:
  push:
    branches:
      - github-actions-node
jobs:
  test-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.19.0'
      - run: echo "$(node -v)"
