name: use workflow_dispatch to study github-actions

on: workflow_dispatch
jobs:
  connect-to-scp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo ${{ github.workspace }}
      - run: echo $(pwd)
      - name: List files in the repository
        run: "ls"
      - name: 通过ppleboy/scp-action 复制文件
        uses: appleboy/scp-action@v1
        with:
          host: 106.14.18.67
          port: 22
          key: ${{ secrets.MY_PRIVATE_KEY }}
          username: admin
          source: src
          target: /home/admin/