name: nodejs-github-actions-study

on: workflow_dispatch
jobs:
  connect-to-scp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: "echo $(pwd)"
      - run: "echo ${{ github.workspace }}"
      - run: "cd ${{ github.workspace }}"
      - run: "echo $(pwd)"
      - name: List files in the repository
        run: |
          "ls"